### ISSUE TITLE
Specifying visitFileAST prevents other hooks from being called

### ISSUE THREAD

**Issue by ogrady** [eliben/pycparser#136]
Defining a `visit_FileAST` method causes other hooks that are nested within the AST not to be called. 
Ex. having `visit_While` works fine but as soon as` visit_FileAST` `visit_While` no longer gets called.

**Comment by eliben** [comment]
This is by design, and is standard behavior for AST visiting functions. It mimics Python's own AST module (described in https://docs.python.org/dev/library/ast.html?highlight=ast#ast.NodeVisitor)

If you override `visit_FOO`, it's assumed that you have some ideas of custom processing of `FOO`. You can always propagate visitation to the children of `FOO` by invoking `self.generic_visit(node)` from the visitor.
