### ISSUE TITLE
Calling parse multiple times

### ISSUE THREAD

**Issue by serpilliere** [eliben/pycparser#207]
Hi!
I wish to parse multiple inputs, and there are `typedef` dependencies needed by the second input declared in the first input. To be clear:

```python
from pycparser import c_parser, c_ast

text_1 = """
typedef struct test_st {
    int a;
} Test;
"""

text_2 = """
struct test_include {
    Test b;
};
"""

parser = c_parser.CParser()
parser.parse(text_1, filename='<stdin>')
parser.parse(text_2, filename='<stdin>')
```

It seems that `typedef` tokens are stored in the `_scope_stack`. This variable is reset at each call of `parse`, so the previous `typedefs` are lost. 

Actually, I can do the trick by calling directly `parser.cparser.parse` the same way as in `parse`.
Is it a valid solution to you, or is there any other way to do this?

Thanks

**Comment by eliben** [comment]
That's a rather unusual problem to have, due to the semantics of how C headers and types work (typically the compilation unit has to be complete w.r.t. types). But it's certainly possible to rig pycparser to do this. You could feed typedefs from the first file back into the second (perhaps by using `c_generator` to re-emit C from it), or what you propose
