### ISSUE TITLE
Coord Line of iffalse in an if-else statement

### ISSUE THREAD

**Issue by Knightto2112** [eliben/pycparser#282]
I tried to parse some C code with pycparser. I'm using the your sample code, func_defs.py as base.

I want to get the line in which the "else" word appear on the source code. I used visit_If to visit if-else statement as follows

```
def visit_If(self, node):
   if node.iffalse is not None:
      else_node = node.iffalse
      else_node.show(showcoord=True)
      self.generic_visit(else_node)
```

Using a sample code below
```
int main()
{
    int x = 0;
    int y = 1;

    if(x == 0)
    {
        x++;
    }
    else
    {
        y++;
    }
}
```

The output of it is:
```
Compound:  (at ./code.c:11:1)
  UnaryOp: p++ (at ./code.c:12:9)
    ID: y (at ./code.c:12:9)
```

Line 11 points to "{". There is no indication on what line "else" appeared on the code.

**Comment by eliben** [comment]
Yes, this is true. The AST represents the semantics of the program, not its syntax. Therefore in the `iffalse` child of `If` nodes we store the actual statement that the `else` points to, and we don't keep the syntactic information of the `if` itself. That's by design in pycparser, since it's mainly used for analyzing the semantics (the AST) and not the exact locations.

There are hacks around it if you *really* need it, like using the lexer `CLexer` to tokenize the same file and find the `else` keyword closest to the coordinate of `ifelse`, but I expect you'll run into more issues of the same kind if you really need the exact locations of keywords in the AST.
