### ISSUE TITLE
voidpf not defined by fake_lib/zlib.h

### ISSUE THREAD

**Issue by thoni56** [eliben/pycparser#366]
Standard `zlib.h` defines `voidpf` which is not defined by `fake_typedefs.h`. I suppose that since `fake_lib` catches `zlib.h` so should define all things in `/usr/include/zlib.h` and thus `/usr/include/zconf.h`.

My hack for fixing it for me was to send the following CPP arguments:

    -Dvoidpf=int -DuInt=int

**Comment by eliben** [comment]
The goal of the fake headers in utils is not to replicate every `typedef` from every common C library. In the limit, this will lead to its own problems because these definitions can collide and create new problems. I'm sort of OK adding typedef for prefixed types (e.g. some library "foo" prefixes all its type names with "foo"), but very common typedefs like `voidp` or `voidpf` are more problematic.

It's perfectly fine, and even desirable for a tool relying on pycparser to define its own careful set of headers. In many cases, headers like `zlib.h` can just be included directly and not faked at all.

**Comment by thoni56** [comment]
Sure, I understand that. But why is there then a `utils/fake_libc_include/zlib.h`?

This gets picked up by CPP and used, shadowing the real `zlib.h`. I thought that was intentional.

**Comment by eliben** [comment]
You're right about that. The fake includes have always evolved organically, as I don't see them as a core part of the project per-se. It's almost impossible to do right by *all* users here, so it's just a collection of compromises.

Since `zlib.h` is already there, I will reopen the issue. Feel free to submit a PR that adds zlib's types.

**Comment by thoni56** [comment]
I think the `fake_libc` is a wonderful addition to the project, and I totally understand the balancing act to keep it small, but cover enough that it continues to be valuable to many.

Is removing `zlib.h` a valid option? Do you know the driving force for adding it in the first place?

**Comment by eliben** [comment]
`zlib.h` was added in 6c5d15d2a035948cb6c83d7331b276a43634071f a few years ago when I was building up `fake_libc_include` to be sufficient to parse some large C OSS projects.

I'd say we keep it since it's already there.

In general if a project is using pycparser I'd recommend that project to have its own version of fake headers which can be use `utils/fake_libc_include` as a baseline.

**Comment by eliben** [comment]
Fixed by #368
