### ISSUE TITLE
c_ast.Node subclasses don't call __init__ on node

### ISSUE THREAD

**Issue by pdietl** [eliben/pycparser#383]
I am trying to use this library to find certain function calls and find the type of argument.
To do this, I have gone the route of trying to add a parent to each node dynamically, by overriding the `generic_visit` method of `c_ast.NodeVisitor`. However, overriding `c_ast.Node`'s `__init__` function to create a `self.parent` attribute doesn't work since none of `c_ast.Node`'s subclasses call `super().__init__`.

Would it be reasonable to accept a PR that fixes this?

**Comment by pdietl** [comment]
Also I can't any instance variables on the fly because of the use of `__slots__`

**Comment by eliben** [comment]
It's not clear to me why you need to `__init__` a `Node`. This type is more like an interface than a data structure - it has no fields, only methods. You can add fields to Python objects dynamically if you wish, I don't see why a `super` call is needed for that.

`__slots__` was added to pycparser a long time ago (in commit 00de62cdc8) since it provides a significant saving in memory. I'm sure many users rely on lower memory consumption now, so `__slots__` are here to stay.
