### ISSUE TITLE
Parsing '//' comments

### ISSUE THREAD

**Issue by juanfgarcia** [eliben/pycparser#464]
I'm getting an error when parsing '//' style comments and not with '/*...*/' style

I've been searching and I've found in pycparser/ply/ctokens.py

```
# Comment (C-Style)
def t_COMMENT(t):
    r'/\*(.|\n)*?\*/'
    t.lexer.lineno += t.value.count('\n')
    return t

# Comment (C++-Style)
def t_CPPCOMMENT(t):
    r'//.*\n'
    t.lexer.lineno += 1
    return t
```

But changing t_COMMENT(t) to the // style doesn't work.

Is there any option to compile with the C++ style? If not, do I need to run yacc or other tool to make it work?

**Comment by eliben** [comment]
https://github.com/eliben/pycparser#31interaction-with-the-c-preprocessor

**Comment by cellularmitosis** [comment]
@eliben first, thank you so much for your amazing blog and for pycparser.

> The preprocessor is supposed to remove all comments.

I think I found the root cause behind the high volume of these "comments don't work" issues.

It looks like this is a clang vs gcc issue: gcc's cpp removes comments while clang's does not (and clang is the default for macOS users, which is likely where these issue reports are coming from).

```
$ cat foo.c 
int foo() {
    // this is a comment.
    return 42;
}
```

clang:

```
$ /usr/bin/cpp foo.c 
# 1 "foo.c"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 423 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "foo.c" 2
int foo() {
    // this is a comment.
    return 42;
}
```

gcc:

```
$ /opt/homebrew/bin/cpp-14 foo.c 
# 0 "foo.c"
# 0 "<built-in>"
# 0 "<command-line>"
# 1 "foo.c"
int foo() {

    return 42;
}
```

This appears to be a bug in clang, as `clang --help` describes the `-C` option, but there appears to be no inverse of this option:

```
  -C                      Include comments in preprocessed output
```

The easy solution for macOS users appears to be:

```
brew install gcc
```

and then

```
parse_file(filename, use_cpp=True, cpp_path='/opt/homebrew/bin/cpp-14')
```

or

```
preprocess_file(filename, use_cpp=True, cpp_path='/opt/homebrew/bin/cpp-14')
```

**Comment by cellularmitosis** [comment]
Update: I submitted a PR: https://github.com/eliben/pycparser/pull/569
