### ISSUE TITLE
Make the use of __slots__ optional

### ISSUE THREAD

**Issue by iangray001** [eliben/pycparser#83]
The recent move to use `__slots__` in `c_ast.py` has broken a fair bit of my code. I pickle ASTs with arbitrary extended attributes, and both of these features now fail. Yes, I can work around them. However, in my opinion, the power of pycparser over something faster and more complete like libclang is the flexibility of Python, which `__slots__` undermines. (If speed is required, pypy executes pycparser about 3 times faster than CPython in my testing.) I think `__slots__` should be optional, if possible.

I forked and attempted to do this but this is hard to do in a way which has minimal impact on your code. I'd be willing to help, but I wanted to speak to you before working on a massive PR which you would understandably reject.

Currently my solution is a nasty monkey patch which I run before using pycparser which iterates through all the classes in c_ast.py, replacing them with clone classes with the same `__dict__` as the original but with the `__slots__` and member attributes removed to restore original behaviour.

Link to Reddit discussion for reference - http://www.reddit.com/r/Python/comments/38alfw/trying_to_define_a_class_which_can_optionally_use/

**Comment by eliben** [comment]
Pickling was addressed in https://github.com/eliben/pycparser/issues/82 -- feel free to submit the PR for that.

As for extending nodes vs. `__slots__`, that's a good question, and it's a tradeoff. `__slots__` does make pycparser consume dramatically less memory, and I don't think PyPy would help here. I haven't had any complaints about the limitation of slots until now; on the other hand the memory/perf reduction is important for a number of downstream projects.

Since all the slots that you care about are in generated nodes, all you really need to modify is `_ast_gen.py` to give you nodes without slots. I can accept a patch that will add a command-line flag to `_ast_gen.py` making it optionally omit slots - how does that sound?

**Comment by iangray001** [comment]
I agree that use of `__slots__` should likely remain the default. My tests have it reducing a ~100MB AST to ~40MB.

The issue that I have is that I would like people to be able to use my application without rebuilding pycparser. Maybe I should just suck it up and rewrite everything to use a weak dictionary to hold my extended attributes, it's just quite a big rewrite!

**Comment by eliben** [comment]
Without getting into the particulars of you application or implementation, you can just ship pycparser as a dependency with your app, and build its nodes any way you like. But ultimately this is up to you.
